### ISSUE TITLE
Mailchimp sign up form on Newsletter Index Page needs styling

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail.io#123]
The page https://wagtail.io/this-week-in-wagtail/ has a sign up form and it does not look like it has much or any styling.

Note: Most users will not directly go to this link but it does serve as a useful quick sharing URL for seeing recent posts & signing up.

<img width="1407" alt="Screen Shot 2021-11-10 at 8 26 30 pm" src="https://user-images.githubusercontent.com/1396140/141101626-9cb1dcaa-0de1-4ba5-a119-7224ed5c9657.png">
<img width="1389" alt="Screen Shot 2021-11-10 at 9 01 41 pm" src="https://user-images.githubusercontent.com/1396140/141101630-d2bf96da-c674-46cf-b962-a5d932f78f84.png">

**Comment by gasman** [comment]
It's looking nicer than that for me - CSS intermittently not loading perhaps?
![Screenshot 2021-11-10 at 11 05 10](https://user-images.githubusercontent.com/85097/141102162-e73edc08-0f8d-49b6-8f46-b54e9398e171.png)

**Comment by lb-** [comment]
Ahh yeah, Firefox is blocking it. Non issue I guess.

<img width="1415" alt="Screen Shot 2021-11-10 at 9 12 48 pm" src="https://user-images.githubusercontent.com/1396140/141103208-ae58cf05-8f2f-436e-a525-bb64a374e035.png">
t
