### ISSUE TITLE
Accessibility: fix colour contrast

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail.io#8]

**Comment by thibaudcolas** [comment]
For reference this is what it looks like at the moment:

<img width="577" alt="twiw-link-colors" src="https://user-images.githubusercontent.com/877585/57134843-4ec0da00-6d9f-11e9-973e-36e0f2449b61.png">

**Comment by kaedroho** [comment]
Thanks! That seems to be covered in separate ticket: https://github.com/wagtail/wagtail.io/issues/2

This ticket came from Codebase, but it predates the recent redesign so the specific issues the author was trying to report may have been resolved. We should check to make sure.

**Comment by thibaudcolas** [comment]
Ah, my bad :) Had already forgotten I had created a ticket for that. Should we close this ticket? It's not super clear to me what colour contrast needs fixing beyond the instance that's in #2.

**Comment by kaedroho** [comment]
Yep, let's only open issues for specific issues we find.
